use_frameworks!

platform :ios, '8.0'

target 'TuGoodsDetail_Example' do
  pod 'TuGoodsDetail', :path => '../'

  target 'TuGoodsDetail_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
